let token=localStorage.getItem("fleetToken"), user=JSON.parse(localStorage.getItem("fleetUser")||"null");
let vehicles=[],drivers=[],assignments=[],editingId=null;
const $=id=>document.getElementById(id);
async function api(url,opt={}){opt.headers={...(opt.headers||{}),Authorization:`Bearer ${token}`,"Content-Type":"application/json"};const r=await fetch("/api"+url,opt);const data=await r.json();if(!r.ok)throw Error(data.message||"Request failed");return data}
function init(){if(!token){$("login").classList.remove("hidden");$("app").classList.add("hidden");return} $("login").classList.add("hidden");$("app").classList.remove("hidden");$("userInfo").textContent=`${user.name} • ${user.role.toUpperCase()}`;document.querySelectorAll(".manager-only").forEach(x=>x.style.display=["admin","manager"].includes(user.role)?"":"none");loadAll()}
$("loginForm").onsubmit=async e=>{e.preventDefault();try{let d=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("email").value,password:$("password").value})}).then(r=>r.json());if(!d.token)throw Error(d.message);localStorage.setItem("fleetToken",d.token);localStorage.setItem("fleetUser",JSON.stringify(d.user));token=d.token;user=d.user;init()}catch(e){$("loginMsg").textContent=e.message;$("loginMsg").style.color="red"}};
$("logout").onclick=()=>{localStorage.clear();location.reload()};
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{if(n.id==="logout")return;document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$(n.dataset.page).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");$("pageTitle").textContent=n.dataset.page[0].toUpperCase()+n.dataset.page.slice(1)});
async function loadAll(){try{let d=await api("/dashboard");$("totalVehicles").textContent=d.vehicles.total;$("activeVehicles").textContent=d.vehicles.active;$("totalDrivers").textContent=d.drivers.total;$("unassignedDrivers").textContent=d.unassignedDrivers;$("statusSummary").innerHTML=`Active: <b>${d.vehicles.active}</b> &nbsp; Maintenance: <b>${d.vehicles.maintenance}</b> &nbsp; Inactive: <b>${d.vehicles.inactive}</b>`;vehicles=await api("/vehicles");drivers=await api("/drivers");assignments=await api("/assignments");renderVehicles();renderDrivers();renderAssignments()}catch(e){alert(e.message)}}
function renderVehicles(){let q=($("vehicleSearch")?.value||"").toLowerCase();$("vehicleRows").innerHTML=vehicles.filter(v=>`${v.license_plate} ${v.model} ${v.manufacturer}`.toLowerCase().includes(q)).map(v=>`<tr><td><b>${v.license_plate}</b></td><td>${v.model}</td><td>${v.manufacturer||"-"}</td><td>${v.capacity}</td><td><span class="badge ${v.status}">${v.status}</span></td><td>${v.driver_name||"Unassigned"}</td><td>${["admin","manager"].includes(user.role)?`<button class="action" onclick="openVehicle(${v.id})">Edit</button>`:""}${user.role==="admin"?`<button class="action danger" onclick="delVehicle(${v.id})">Delete</button>`:""}</td></tr>`).join("")}
function renderDrivers(){let q=($("driverSearch")?.value||"").toLowerCase();$("driverRows").innerHTML=drivers.filter(d=>`${d.name} ${d.phone} ${d.license_number}`.toLowerCase().includes(q)).map(d=>`<tr><td>${d.name}</td><td>${d.phone}</td><td>${d.license_number}</td><td>${d.license_expiry||"-"}</td><td><span class="badge ${d.status}">${d.status}</span></td><td>${d.vehicle_plate||"Unassigned"}</td><td>${["admin","manager"].includes(user.role)?`<button class="action" onclick="openDriver(${d.id})">Edit</button>`:""}${user.role==="admin"?`<button class="action danger" onclick="delDriver(${d.id})">Delete</button>`:""}</td></tr>`).join("")}
function renderAssignments(){$("assignmentRows").innerHTML=assignments.map(a=>`<tr><td>${a.license_plate}</td><td>${a.driver_name}</td><td>${new Date(a.assigned_at).toLocaleString()}</td><td>${["admin","manager"].includes(user.role)?`<button class="action danger" onclick="endAssignment(${a.id})">Unassign</button>`:""}</td></tr>`).join("")}
function show(title,html,submit){$("modalTitle").textContent=title;$("modalForm").innerHTML=html;$("modalForm").onsubmit=submit;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
function openVehicle(id){editingId=id;let v=vehicles.find(x=>x.id===id)||{};show(id?"Edit Vehicle":"Add Vehicle",`<div class="grid2"><label>License Plate<input id="f1" value="${v.license_plate||""}" required></label><label>Model<input id="f2" value="${v.model||""}" required></label><label>Manufacturer<input id="f3" value="${v.manufacturer||""}"></label><label>Year<input id="f4" type="number" value="${v.year||""}"></label><label>Capacity<input id="f5" type="number" step=".01" value="${v.capacity||""}"></label><label>Status<select id="f6"><option ${v.status==="active"?"selected":""}>active</option><option ${v.status==="maintenance"?"selected":""}>maintenance</option><option ${v.status==="inactive"?"selected":""}>inactive</option></select></label></div><button type="submit">Save Vehicle</button>`,async e=>{e.preventDefault();try{await api(id?`/vehicles/${id}`:"/vehicles",{method:id?"PUT":"POST",body:JSON.stringify({license_plate:$("f1").value,model:$("f2").value,manufacturer:$("f3").value,year:$("f4").value,capacity:$("f5").value,status:$("f6").value})});closeModal();loadAll()}catch(e){alert(e.message)}})}
function openDriver(id){let d=drivers.find(x=>x.id===id)||{};show(id?"Edit Driver":"Add Driver",`<div class="grid2"><label>Name<input id="f1" value="${d.name||""}" required></label><label>Phone<input id="f2" value="${d.phone||""}" required></label><label>Email<input id="f3" type="email" value="${d.email||""}"></label><label>License No.<input id="f4" value="${d.license_number||""}" required></label><label>License Expiry<input id="f5" type="date" value="${d.license_expiry||""}"></label><label>Status<select id="f6"><option ${d.status==="active"?"selected":""}>active</option><option ${d.status==="inactive"?"selected":""}>inactive</option></select></label></div><button type="submit">Save Driver</button>`,async e=>{e.preventDefault();try{await api(id?`/drivers/${id}`:"/drivers",{method:id?"PUT":"POST",body:JSON.stringify({name:$("f1").value,phone:$("f2").value,email:$("f3").value,license_number:$("f4").value,license_expiry:$("f5").value,status:$("f6").value})});closeModal();loadAll()}catch(e){alert(e.message)}})}
function openAssignment(){let freeV=vehicles.filter(v=>!v.driver_name&&v.status==="active"),freeD=drivers.filter(d=>!d.vehicle_plate&&d.status==="active");show("Assign Driver",`<label>Vehicle<select id="f1">${freeV.map(v=>`<option value="${v.id}">${v.license_plate} - ${v.model}</option>`).join("")}</select></label><label>Driver<select id="f2">${freeD.map(d=>`<option value="${d.id}">${d.name} - ${d.license_number}</option>`).join("")}</select></label><button type="submit">Assign</button>`,async e=>{e.preventDefault();try{await api("/assignments",{method:"POST",body:JSON.stringify({vehicle_id:$("f1").value,driver_id:$("f2").value})});closeModal();loadAll()}catch(e){alert(e.message)}})}
async function delVehicle(id){if(confirm("Delete this vehicle?")){await api("/vehicles/"+id,{method:"DELETE"});loadAll()}}
async function delDriver(id){if(confirm("Delete this driver?")){await api("/drivers/"+id,{method:"DELETE"});loadAll()}}
async function endAssignment(id){if(confirm("End this assignment?")){await api("/assignments/"+id,{method:"DELETE"});loadAll()}}
init();